version: '3.7'

services:

  webs:
    image: node:lts-buster
    container_name: alterint
    volumes:
      -  ~/.aws:/home/node/.aws
      - ~/.git-credentials:/home/node/.git-credentials
      - ~/.gitconfig:/home/node/.gitconfig
      - .:/home/node/app
    user: node
    working_dir: /home/node/app
    command: tail -f /dev/null

